### ISSUE TITLE
what are width and precision in options?

### ISSUE THREAD

**Issue by sorokinvj** [gfiorello/ffmpeg-peaks#3]
Should I provide width based on audio length? 

What is precision?

**Comment by t4nz** [comment]
Sorry for my late reply. I hope this information will be helpful to you.

> Should I provide width based on audio length?

No. Is the width of the area that should be drawn (in pixel).
> What is precision?

Is the number of samples that you want to analyze. Es. 1 = Each sample  of the audio is analyzed

**Comment by sorokinvj** [comment]
Thanks!
